// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	domain "section9/domain"

	mock "github.com/stretchr/testify/mock"
)

// CarRepository is an autogenerated mock type for the CarRepository type
type CarRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: car
func (_m *CarRepository) Create(car *domain.Car) (*domain.Car, error) {
	ret := _m.Called(car)

	var r0 *domain.Car
	if rf, ok := ret.Get(0).(func(*domain.Car) *domain.Car); ok {
		r0 = rf(car)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Car)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Car) error); ok {
		r1 = rf(car)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: car
func (_m *CarRepository) Delete(car *domain.Car) (bool, error) {
	ret := _m.Called(car)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*domain.Car) bool); ok {
		r0 = rf(car)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Car) error); ok {
		r1 = rf(car)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *CarRepository) FindAll() ([]domain.Car, error) {
	ret := _m.Called()

	var r0 []domain.Car
	if rf, ok := ret.Get(0).(func() []domain.Car); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Car)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ID
func (_m *CarRepository) FindByID(ID int) (*domain.Car, error) {
	ret := _m.Called(ID)

	var r0 *domain.Car
	if rf, ok := ret.Get(0).(func(int) *domain.Car); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Car)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: car
func (_m *CarRepository) Update(car *domain.Car) (bool, error) {
	ret := _m.Called(car)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*domain.Car) bool); ok {
		r0 = rf(car)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Car) error); ok {
		r1 = rf(car)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateGarage provides a mock function with given fields: ID, garageID
func (_m *CarRepository) UpdateGarage(ID int, garageID int) (bool, error) {
	ret := _m.Called(ID, garageID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(ID, garageID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(ID, garageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
